# Generated by Django 5.0.1 on 2025-01-02 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('users_from_ip', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IP addresses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('last_completed_time', models.DateTimeField(blank=True, null=True)),
                ('is_public_name', models.BooleanField(default=False)),
                ('current_level', models.IntegerField(default=0)),
                ('discord_id', models.IntegerField(default=0)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('is_public_organization', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_reason', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.JSONField(default=list)),
                ('ip_address_count', models.IntegerField(default=0)),
                ('avatar', models.URLField(default='https://api.dicebear.com/9.x/fun-emoji/svg?seed=Easton&backgroundColor=059ff2,71cf62,d84be5,d9915b,f6d594,fcbc34,b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('rank', models.CharField(blank=True, default='0', max_length=5)),
                ('last_verification_email_sent', models.DateTimeField(blank=True, null=True)),
                ('verification_emails_sent', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
