# Generated by Django 5.0.1 on 2024-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_last_completed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
