# Generated by Django 5.0.1 on 2025-01-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_last_completed_time'),
        ('accounts', '0003_generate_avatars'),
    ]

    operations = [
    ]
